<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>sm.clagenna</groupId>
		<artifactId>stdcla</artifactId>
		<version>0.10-SNAPSHOT</version>
	</parent>
	<artifactId>stdc_pdf</artifactId>
	<packaging>jar</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- gia definito nel POM padre -->
		<!-- javafx.version>23.0.1</ javafx.version -->
	    <common.text.version>1.13.0</common.text.version>
	    <apache.pdfbox.version>2.0.35</apache.pdfbox.version>
	    <pdf2dom.version>2.0.3</pdf2dom.version>
	    <logback.version>1.5.18</logback.version>
	</properties>
	<dependencies>
		<!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
		<dependency>
			<groupId>sm.clagenna</groupId>
			<artifactId>stdc_utils</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>sm.clagenna</groupId>
			<artifactId>stdc_sql</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-fxml -->
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-fxml</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-web -->
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>16</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-media -->
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-media</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<!-- https://www.baeldung.com/pdf-conversions-java  -->
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>${apache.pdfbox.version}</version>
		</dependency>
		<dependency>
			<groupId>net.sf.cssbox</groupId>
			<artifactId>pdf2dom</artifactId>
			<version>${pdf2dom.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-text</artifactId>
			<version>${common.text.version}</version>
		</dependency>
<!--		Pensavo potesse servire per mascherare i log del org.mabb.fontverter.opentype.TtfInstructions.TtfInstructionParser.class
		purtroppo non ne è valsa la pena questa strada
-->	
	<!-- dependency>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-core</artifactId>
          <version>${logback.version}</version>
        </dependency>
        <dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${logback.version}</version>
		</dependency>
  -->
		
	</dependencies>
</project>
